# Git backend
spring.cloud.config.server.git.uri=file:///${HOME}/g1patil/spring-cloud-config-bus-kafka/test-repo
spring.cloud.config.server.git.force-pull=true
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=${BITBUCKET_BRANCH:main}