# Vault backend
spring.cloud.config.server.vault.host=localhost
spring.cloud.config.server.vault.port=8200
spring.cloud.config.server.vault.scheme=http
spring.cloud.config.server.vault.authentication=TOKEN
spring.cloud.config.server.vault.token=${VAULT_TOKEN}
spring.cloud.config.server.vault.kv-version=2
spring.cloud.config.server.vault.backend=secret
spring.cloud.config.server.vault.default-key=application